const mongoose = require('mongoose');

const inventSchema = new mongoose.Schema({
    PropType:{
        type:String,
    },
    number:{
        type:String,
    },
    size:{
        type:String,
    },
    icity:{
        type:String,
    },
    subLoc:{
        type:String,
    },
    width:{
        type:String,
    },
    len:{
        type:String,
    },
    ta:{
        type:String,
    },
    metrics:{
        type:String,
    },
    direction:{
        type:String,
    },
    facing:{
        type:String,
    },
    road:{
        type:String,
    },
    near:{
        type:String,
    },
    ownership:{
        type:String,
    },
    ownerName:{
        type:String,
    },
    MobileNumber:{
        type:String,
    },
    Email:{
        type:String,
    },
    lastcontact:{
        type:Date,
    },
    fathername:{
        type:String,
    },
    Address:{
        type:String,
    },
    HouseNo:{
        type:String,
    },
    Location:{
        type:String,
    },
    Sublocation:{
        type:String,
    },
    City:{
        type:String,
    },
    Pincode:{
        type:String,
    },
    State:{
        type:String,
    },
    Pcountry:{
        type:String,
    },
    ptype:{
        type:String,
        default:"Residential"
    },
    
    bdate:{
        type:String,
        default:Date.now(),
    },
    subcategory:{type:String,},
    unittype:{type:String,},
    carpetarea:{type:String,},
    floorT:{type:String,},
    floorOn:{type:String,},
    totalB:{type:String,},
    buildarea:{type:String,},
    carpetarea:{type:String,},
    terracearea:{type:String,},
    groundfloor:{type:String,},
    secondfloor:{type:String,},
    thirdfloor:{type:String,},
    age:{type:String,},
    balcony:{type:String,},
    furnished:{type:String,},
    amenities:{type:String,},
    exPrice:{type:String,},
    Priceper:{type:String,},
    QuotePrice:{type:String,},
    cat:{type:String,},
    online:{type:String,},
    CommunicationDate:{type:String,},
    FollowUpDate:{type:String,},
    RentAmmount:{type:String,},
    LockInPeriod:{type:String,},
    SecurityDeposit:{type:String,},
    MaintanenceCharge:{type:String,},
    RentEscallation:{type:String,},
    TotalRent:{type:String,},
    FitoutPeriod:{type:String,},
    User:{type:String,},

    created:{
        type:Date,
        required:true,
        default:Date.now(),
    }
})



module.exports = mongoose.model('Invent',inventSchema);